name: CI

on:
  push:
    branches:
      - main # Ensure this matches the branch you're pushing to

jobs:
  build:
    runs-on: windows-latest # Or windows-latest if you need Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '20.11.0' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build React app
        run: npm run build
