name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # Or 'ubuntu-latest' for a Linux environment

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Set your preferred Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install # Use 'yarn install' if you're using Yarn

      # Step 4: Run tests
      - name: Run tests
        run: npm test -- --watchAll=false # Ensure tests run once and exit

      # Step 5: Build the React app (optional, can be useful for deployment)
      - name: Build app
        run: npm run build
